### Create book
POST localhost:8080/books/create
Content-Type: application/x-www-form-urlencoded

title=Test title&rating=7

### Create book with random generated entries
POST localhost:8080/books/create
Content-Type: application/x-www-form-urlencoded

title={{$random.alphabetic(10)}}&rating={{$random.integer(10)}}&publisherId=1&authorIds=1

### Get book
GET localhost:8080/books/get?id=1

### Create book - for task 1 (with Publisher id)
POST localhost:8080/books/create
Content-Type: application/x-www-form-urlencoded

title=Book 2&rating=5&publisherId=2

### Create book - for task 2 (with Publisher id and List of Author ids)
POST localhost:8080/books/create
Content-Type: application/x-www-form-urlencoded

title={{$random.alphabetic(10)}}&rating={{$random.integer(10)}}&publisherId=3&authorIds=2&authorIds=4

### Get book
GET localhost:8080/books/get?id=1

### Update book
POST localhost:8080/books/update
Content-Type: application/x-www-form-urlencoded

id=1&title=Abc2&rating=8

### Delete book
POST localhost:8080/books/delete
Content-Type: application/x-www-form-urlencoded

id=8




### Get all books
GET localhost:8080/books

### Get all by rating
GET localhost:8080/books/byRating?rating=7

### Get all with publisher
GET localhost:8080/books/withPublisher

### Get all by publisher
GET localhost:8080/books/byPublisher?publisherId=1

### Get all by author
GET localhost:8080/books/byAuthor?authorId=2